// ES6 module syntax
import LocalizedStrings from 'react-localization';

let locdb = new LocalizedStrings({
 en:{
    headerHome: "Home",
    headerFile:"File",
    headerConfiguration: "Configuration",
    headerHelp:"Help",
    headerDiscord: "Discord",

    navigatorCharacter: "Character",
    navigatorPowers: "Powers",
    navigatorBoons: "Boons",
    navigatorCompanions: "Companions",
    navigatorMounts: "Mounts",
    navigatorStatistics: "Statistics",
    navigatorOptimization: "Optimization",

    configurationLanguage: "Language",

    fileImport: "Import",
    fileExport: "Export",

    characterEquipment: "Gear",
    characterItem: "Item",
    characterModification: "Modification",
    characterEnhancements: "Enchantments and Artifacts",
    characterEnchantmentsOffensive: "Offensive Slots",
    characterEnchantmentsDefensive: "Defensive Slots",
    characterArtifacts: "Artifacts",
    characterOverloads: "Overloads",
    characterOtherEnchantments: "Other Enchant.",

    boonsTier: "Tier",
    boonsCampaigns: "Campaigns",
    boonsGuild: "Guild Stronghold",
    boonsMasterBoons: "Master Boons",
    boonsChooseOne: "Choose One",
    boonsChooseTwo: "Choose Two",
    boonsOffense: "Offense",
    boonsDefense: "Defense",
    boonsUtility: "Utility",
    boonsGuildLevel: "Guild Level",

    statisticsAttribute: "Attribute",
    statisticsRatings: "Ratings",
    statisticsPercentage: "Percentage",
    statisticsPower: "Power",
    statisticsAccuracy: "Accuracy",
    statisticsCombatAdvantage: "Combat Advantage",
    statisticsCriticalStrike: "Critical Strike",
    statisticsCriticalSeverity: "Critical Severity",
    statisticsDefense: "Defense",
    statisticsAwareness: "Awareness",
    statisticsCriticalAvoidance: "Critical Avoidance",
    statisticsDeflect: "Deflect",
    statisticsDeflectSeverity: "Deflect Severity",
    statisticsForte: "Forte",
    statisticsControlBonus: "Control Bonus",
    statisticsControlResistance: "Control Resistance",
    statisticsIncomingHealing: "Incoming Healing",
    statisticsOutgoingHealing: "Outgoing Healing",
    statisticsActionPointGain: "Action Point Gain",
    statisticsRechargeSpeed: "Recharge Speed",
    statisticsMovementSpeed: "Movement Speed",
    statisticsStaminaRegeneration: "Stamina Regeneration",
    statisticsPhysicalDamageBoost: "Physical Damage Boost",
    statisticsMagicalDamageBoos: "Magical Damage Boost",
    statisticsGoldBonus: "Gold Bonus",
    statisticsGloryBonus: "Glory Bonus",
    statisticsBoosts: "Boosts"
 },
 pt: {
    headerHome: "Início",
    headerFile:"Arquivo",
    headerConfiguration: "Configuração",
    headerHelp:"Ajuda",
    headerDiscord: "Discord",

    navigatorCharacter: "Personagem",
    navigatorPowers: "Poderes",
    navigatorBoons: "Dádivas",
    navigatorCompanions: "Companheiros",
    navigatorMounts: "Montarias",
    navigatorStatistics: "Estatísticas",
    navigatorOptimization: "Otimização",

    configurationLanguage: "Idioma",

    fileImport: "Importar",
    fileExport: "Exportar",

    characterEquipment: "Equipamento",
    characterItem: "Item",
    characterModification: "Modificação",
    characterEnhancements: "Encantamentos e Artefatos",
    characterEnchantmentsOffensive: "Encant. Ofensivos",
    characterEnchantmentsDefensive: "Encant. Defensivos",
    characterArtifacts: "Artefatos",
    characterOverloads: "Sobrecargas",
    characterOtherEnchantments: "Outros Encant.",

    boonsTier: "Camada",
    boonsCampaigns: "Campanhas",
    boonsGuild: "Stronghold da Guilda",
    boonsMasterBoons: "Dádivas Mestre",
    boonsChooseOne: "Escolha Uma",
    boonsChooseTwo: "Escolha Duas",
    boonsOffense: "Ofensivos",
    boonsDefense: "Defensivos",
    boonsUtility: "Utilitários",
    boonsGuildLevel: "Nível da Guilda",

    statisticsAttribute: "Atributo",
    statisticsRatings: "Valores",
    statisticsPercentage: "Porcentagem",
    statisticsPower: "Poder",
    statisticsAccuracy: "Acurácia",
    statisticsCombatAdvantage: "Vantagem de Combate",
    statisticsCriticalStrike: "Acerto Crítico",
    statisticsCriticalSeverity: "Severidade de Crítico",
    statisticsDefense: "Defesa",
    statisticsAwareness: "Percepção",
    statisticsCriticalAvoidance: "Evasão de Críticos",
    statisticsDeflect: "Desvio",
    statisticsDeflectSeverity: "Severidade de Desvio",
    statisticsForte: "Ponto Forte",
    statisticsControlBonus: "Bonus de Controle",
    statisticsControlResistance: "Resitência a Controle",
    statisticsIncomingHealing: "Entrada de Cura",
    statisticsOutgoingHealing: "Saída de Cura",
    statisticsActionPointGain: "Ganho de Pontos de Ação",
    statisticsRechargeSpeed: "Velocidade de Recarga",
    statisticsMovementSpeed: "Velocidade de Movimento",
    statisticsStaminaRegeneration: "Regeneração de Energia",
    statisticsPhysicalDamageBoost: "Aumento de Dano Físico",
    statisticsMagicalDamageBoos: "Aumento de Dano Mágico",
    statisticsGoldBonus: "Bônus de Ouro",
    statisticsGloryBonus: "Bônus de Glória",
    statisticsBoosts: "Aumentos"
 }
});

export default locdb;